import{a as v,i as l,S as x}from"./assets/vendor-BGz2EIcA.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="46968352-3644d680d7f4886b7770d091e";async function y(t,r=1,a=20){const i=new URLSearchParams({key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:a}),{data:e}=await v(`https://pixabay.com/api/?${i}`);return e}function b(t){return t.map(({webformatURL:r,largeImageURL:a,tags:i,likes:e,views:o,comments:d,downloads:S})=>`<li class="gallery-card">
      <a class="card-link" href="${a}">
    <img class="card-image" src="${r}" alt="${i}"/>
    </a>
    <ul class="card-info">
    <li class="params-item-value"><h2 class="textBold">Likes</h2> <p class="amount">${e}</p></li>
    <li class="params-item-value"><h2 class="textBold">Views</h2> <p class="amount">${o}</p></li>
    <li class="params-item-value"><h2 class="textBold">Comments</h2> <p class="amount">${d}</p></li>
    <li class="params-item-value"><h2 class="textBold">Downloads</h2> <p class="amount">${S}</p></li>
    </ul>
    </li> `).join("")}const f=document.querySelector(".gallery"),L=document.querySelector(".form-container"),p=document.querySelector(".loader"),s=document.querySelector(".load-btn"),h={titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",icon:"ico-warning",iconColor:"#fff",iconUrl:"../img/bi_x-octagon.svg",close:!1};L.addEventListener("submit",P);s.addEventListener("click",B);let c=1;const m=15;let u;n(s);async function P(t){if(t.preventDefault(),u=t.currentTarget.elements.query.value.trim(),u!==""){f.innerHTML="",g(p),c=1;try{const r=await y(u,c,m);if(u.includes(" ")){l.info({message:"Query should not contain spaces.",...h}),n(s);return}if(r.hits.length===0){l.info({message:"Photos not found, try another query",...h}),n(f),n(s);return}L.reset(),f.innerHTML=b(r.hits),c*m>=r.totalHits?(l.info({message:"We're sorry, but you've reached the end of search results."}),n(s)):g(s),w.refresh()}catch{l.error({message:"Something went wrong",...h})}finally{n(p)}}}async function B(){c+=1,s.disabled=!0;try{const t=await y(u,c,m);console.log(t),f.insertAdjacentHTML("beforeend",b(t.hits)),w.refresh(),c*m>=t.totalHits?(l.info({message:"We're sorry, but you've reached the end of search results."}),n(s)):g(s);const a=document.querySelector(".gallery-card").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch{l.error({message:"Something went wrong"})}finally{s.disabled=!1}}let w=new x(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){t.classList.remove("hidden")}function n(t){t.classList.add("hidden")}
//# sourceMappingURL=index.js.map
